### ISSUE TITLE
Функциональность главного оконного приложения 

### ISSUE THREAD

**Issue by IgnatievAnton** [IgnatievAnton/Chat#14]

**Comment by IgnatievAnton** [comment]
На главном окне должен быть список пользователей , окно группового чата и строка для набора сообщений.Так же при нажатии на пользователя из списка пользователя создается новая вкладка с этим пользователем.

**Comment by IgnatievAnton** [comment]
nuw build version 8

**Comment by haritonasty** [comment]
на главном окне все отображается. при нажатии на пользователя создается новая вкладка с ним. работает корректно. протестировано в v8
