### ISSUE TITLE
Функциональность отдельных пользовательских оконных чатов

### ISSUE THREAD

**Issue by IgnatievAnton** [IgnatievAnton/Chat#17]

**Comment by IgnatievAnton** [comment]
Реализация окон внутри приложения в виде вкладок при нажатии на которые будет открываться данная вкладка и внутри нее производится обмен сообщениями

**Comment by IgnatievAnton** [comment]
clientProject version 11

**Comment by IgnatievAnton** [comment]
nuw build version 8

**Comment by haritonasty** [comment]
функциональность протестирована в v8
